import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    products: [
      {
        id: 1,
        title: "Product 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 50000,
        saleOff: 0.1,
        selectedProduct: 0,
        ratings: 3,
        reviews: 5,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 10,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 0,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 2,
        title: "Product 2",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 35000,
        saleOff: 0.2,
        selectedProduct: 1,
        ratings: 5,
        reviews: 10,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        image: "img1",
        quantity: 15,
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 3,
        title: "Product 3",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 110000,
        saleOff: 0.3,
        selectedProduct: 0,
        ratings: 2,
        reviews: 3,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 10,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 0,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 4,
        title: "Product 4",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 50000,
        saleOff: 0.4,
        selectedProduct: 0,
        ratings: 1,
        reviews: 0,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 15,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 5,
        title: "Product 5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 35000,
        saleOff: 0.5,
        selectedProduct: 0,
        ratings: 4,
        reviews: 2,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 15,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 6,
        title: "Product 6",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 110000,
        saleOff: 0.6,
        selectedProduct: 0,
        ratings: 5,
        reviews: 1,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 15,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 7,
        title: "Product 7",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 50000,
        saleOff: 0.7,
        selectedProduct: 0,
        ratings: 5,
        reviews: 7,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 15,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 8,
        title: "Product 8",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 35000,
        saleOff: 0.8,
        selectedProduct: 0,
        ratings: 3,
        reviews: 0,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 15,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
      {
        id: 9,
        title: "Product 9",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
        price: 110000,
        saleOff: 0.9,
        selectedProduct: 0,
        ratings: 4,
        reviews: 2,
        isAddedToCart: false,
        isAddedBtn: false,
        isFavourite: false,
        quantity: 15,
        image: "img1",
        listProductDetail: [
          {
            image: "blueImg1",
            quantity: 10,
            textColor: "Hộp màu xanh",
          },
          {
            image: "redImg1",
            quantity: 5,
            textColor: "Hộp màu đỏ",
          },
        ],
      },
    ],
    userInfo: {
      isLoggedIn: false,
      isSignedUp: false,
      hasSearched: false,
      name: "",
      productTitleSearched: "",
    },
    systemInfo: {
      openLoginModal: false,
      openSignupModal: false,
      openCheckoutModal: false,
    },
  },
  mutations: {},
  actions: {},
  modules: {},
});
